config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'
  
  resources :lists, param: :slug
  resources :products
  resources :contacts
  match '/upload', to: 'products#upload', via: :post
  match '/delete_price', to: 'products#delete_price', via: :get
  match '/remove_from_list', to: 'lists#remove_product', via: :delete
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user

  def title
    "Список " +
    List
      .where(session_id: session_id)
      .first
      .created_at
      .strftime('%d-%m-%Y')
  end

  def codes_list
    self.product_codes.split(",").select { |v| v != "" }
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    token = Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64)

    if current_user
      current_user.update_attributes(current_session_id: token)
    else
      cookies[:session_id] = token
    end

    redirect_to products_path
  end

  def index
    @lists = current_user.lists
  end

  def show
    @session_id = params[:slug]
    @list = Product.user_list(@session_id)

    @grid = ProductsGrid.new(params[:products_grid]) do |scope|
      @list.page(params[:page]).per(50)
    end

    @codes_list = List.find_by(session_id:@session_id).codes_list
    @amount = 0

    @list.each do |product|
      @amount += @codes_list.count(product.code) * product.price
    end

    @amount = @amount.round(2)

    if current_user
      current_user.update_attributes(current_session_id: @session_id)    
      @lists = current_user.lists 
    end

  end

  def create
    if current_user
      @session_id = current_user.current_session_id
    else
      @session_id = cookies[:session_id]
    end

    @list = List.find_by(session_id: @session_id) 

    if @list
      @list.product_codes += "#{params[:product_codes]},"
    else
      @list = List.new(list_params)
      @list.product_codes = ",#{params[:product_codes]},"
      @list.session_id = @session_id
    end

    if current_user
      current_user.update_attributes(current_session_id: @session_id)
      @list.user_id = current_user.id
    end

    @code = params[:product_codes]
    list = List.find_by(session_id: @session_id)
    @codes_list = list.codes_list if list

    @list.save
  end

  def remove_product
    if current_user
      @session_id = current_user.current_session_id
    else
      @session_id = cookies[:session_id]
    end

    @list = List.find_by(session_id: @session_id) 
    codes = @list.product_codes.sub(params[:code],'').sub(/,,/,',')
    @list.update_attributes(product_codes: codes) if @list
    @code = params[:code]
    if codes == ','
      @list.destroy 

      if current_user
        if current_user.lists.present?
          current_user.update_attributes(current_session_id: current_user.lists.last.session_id)
        else
          current_user.update_attributes(current_session_id: nil)
        end
      end
    end
  end

  def destroy
    list = List.find_by(session_id: params[:slug])
    list.destroy

    redirect_to lists_path
  end

  private

    def list_params
      params.permit(:product_codes)
    end

end

app/views/lists/create.js.erb
var product_count_tag = $('.product-count-<%= @code %>');
var product_count = parseInt(product_count_tag.find('span').text());
product_count_tag.fadeIn().addClass('pressed')
  .find('span')
  .text(product_count + 1);
if (product_count > 0) {
  var price_tag = product_count_tag.closest('tr').find('td.price span');
  var price_single = parseFloat(price_tag.data("price"));
  price_tag.text( price_single + " р. (" + (price_single*(product_count + 1)).toFixed(2) + "\xa0р.)" );
}

var count_tag = $('.products-count');
var amount_count = count_tag.text().length > 0 ? parseInt(count_tag.text()) : 0;
count_tag.text(amount_count + 1);
count_tag.fadeIn();

var table_list_div = $('.table-list');
if (table_list_div.length > 0) {
  var amount_td = table_list_div
                      .find('tbody tr')
                      .last()
                      .find('td')
                      .last();
  amount = parseFloat(amount_td.text());
  amount_td.text((amount + price_single).toFixed(2) + " р.");
}

app/views/lists/index.html.erb
<%= render 'layouts/products_header' %>

<div class="container text-center">
  <ul>
    <% for list in @lists %>
      <li>
        <%= link_to list.title, list_path(slug: list.session_id) %>
        <%= link_to "удалить", list_path(slug: list.session_id), 
          method: :delete, data: { confirm: "Вы уверены?" },
          style: "margin-left: 30px; color: gray;" %>
      </li>
    <% end %>
  </ul>

  <%= link_to "Начать новый список", new_list_path %>
</div>

app/views/lists/index.xls.erb
<table border="1">
  <tr>
    <td colspan="6">Прайс-лист фирмы ИП Осипов Сергей Васильевич (по всем разделам) за <%= Time.now.strftime("%d.%m.%Y") %></td>

  </tr>
  <tr><td></td><td></td><td></td><td></td><td></td><td></td></tr>
  <tr><td></td><td></td><td></td><td></td><td></td><td>=СУММ(F5:F27242)</td></tr>
  <tr>
    <th>Наименование товара</th>
    <th>Ед.</th>
    <th>Опт.цена</th>
    <th>Вал</th>
    <th>Кол.</th>
    <th>Сум.заказа</th>
  </tr>
  <% @list.each_with_index do |product, i| %>
    <% row = i + 5 %>
    <tr>
      <td><%= product.full_name %></td>
      <td>шт.</td>
      <td><%= product.price %></td>
      <td>руб</td>
      <td><%= product.quantity_in_list @session_id %></td>
      <td><%= "=C#{row}*E#{row}" %></td>
    </tr>
  <% end %>
</table>

app/views/lists/remove_product.js.erb
var product_count_tag = $('.product-count-<%= @code %>');
var product_count = parseInt(product_count_tag.find('span').text());
product_count_tag.find('span').text(product_count - 1);
var price_tag = product_count_tag.closest('tr').find('td.price span');
var price_single = parseFloat(price_tag.data("price"));
if (product_count == 1) {
  product_count_tag.fadeOut().removeClass('pressed');
    // .closest('tr').fadeOut(); //УБРАТЬ ИЗ КАТАЛОГА, В СПИСКЕ ОСТАВИТЬ
}
if(product_count > 2) {
  price_tag.text( price_single + " р. (" + (price_single*(product_count - 1)).toFixed(2) + "\xa0р.)" );
} else {
  price_tag.text( price_single + " р." );
}
var count_tag = $('.products-count');
var amount_count =  parseInt(count_tag.text());
count_tag.text(amount_count - 1);
if (amount_count == 1){
  count_tag.fadeOut();
}

var table_list_div = $('.table-list');
if (table_list_div.length > 0) {
  var amount_td = table_list_div
                      .find('tbody tr')
                      .last()
                      .find('td')
                      .last();
  amount = parseFloat(amount_td.text());
  amount_td.text((amount - price_single).toFixed(2) + " р.");
}

app/views/lists/show.html.erb
<%= render 'layouts/products_header' %>

<h1>Список отобранных товаров</h1>
<p class="text-center"><%= link_to "Скачать список в Excel", lists_path(format: 'xls') %></p>

<div class="table-wrapper table-list" data-amount="<%= @amount %>">
  <%= datagrid_table @grid %>
  <%= paginate(@grid.assets, :theme => 'twitter-bootstrap-3',
                              :pagination_class => "pagination-sm") %>
</div>

app/views/lists/show.xls.erb
<table border="1">
  <tr>
    <td colspan="6">Прайс-лист фирмы ИП Осипов Сергей Васильевич (по всем разделам) за <%= Time.now.strftime("%d.%m.%Y") %></td>

  </tr>
  <tr><td></td><td></td><td></td><td></td><td></td><td></td></tr>
  <tr><td></td><td></td><td></td><td></td><td></td><td>=СУММ(F5:F27242)</td></tr>
  <tr>
    <th>Наименование товара</th>
    <th>Ед.</th>
    <th>Опт.цена</th>
    <th>Вал</th>
    <th>Кол.</th>
    <th>Сум.заказа</th>
  </tr>
  <% @list.each_with_index do |product, i| %>
    <% row = i + 5 %>
    <tr>
      <td><%= product.full_name %></td>
      <td>шт.</td>
      <td><%= product.price %></td>
      <td>руб</td>
      <td><%= product.quantity_in_list @session_id %></td>
      <td><%= "=C#{row}*E#{row}" %></td>
    </tr>
  <% end %>
</table>