config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'
  
  resources :lists, param: :slug
  resources :products
  resources :contacts
  match '/upload', to: 'products#upload', via: :post
  match '/delete_price', to: 'products#delete_price', via: :get
  match '/remove_from_list', to: 'lists#remove_product', via: :delete
end

app/models/product.rb
class Product < ApplicationRecord

  mount_uploader :image, ProductUploader

  def self.user_list session_id
    Product.where("code in (?)", List.find_by(session_id: session_id).codes_list)
  end

  def quantity_in_list session_id
    list = List.find_by(session_id: session_id)
    codes_list = list.codes_list if list
    codes_list ? codes_list.count(self.code) : 0
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @grid = ProductsGrid.new(params[:products_grid]) do |scope|
      scope.page(params[:page]).per(50)
    end
    @new_list = List.new

    if current_user
      @session_id = current_user.current_session_id
    else
      @session_id = cookies[:session_id]
    end

    list = List.find_by(session_id: @session_id)
    @codes_list = list.codes_list if list
    @lists = current_user.lists if current_user
    @products = Product.all
  end

  def upload
    if uploaded_io = params[:file]
      old_files = Dir.glob("#{Rails.root}/public/uploads/products/*")
      old_files.each { |f| File.delete(f) }

      dir_name = Rails.root.join('public', 'uploads', 'products')
      FileUtils.mkdir_p(dir_name) unless File.directory?(dir_name)
      
      @filename = DateTime.now.to_s + '.xls'
      path_to_file = dir_name + @filename

      File.open(path_to_file, 'w') do |file|
        file.write(uploaded_io.read.force_encoding("utf-8"))
      end
    end
    redirect_to rails_admin_path
  end

  def delete_price
    old_files = Dir.glob("#{Rails.root}/public/uploads/products/*")
    old_files.each { |f| File.delete(f) }

    redirect_to rails_admin_path
  end
end

app/views/products/_product_form.html.haml
- if model.image.present? 
  = link_to model.image.url, data: { lightbox: 'product-image' }, class: "product-image" do
    = image_tag model.image.thumb.url
= form_tag new_list, remote: true, class: "product-form" do
  = hidden_field_tag :product_codes, model.code
  = button_tag model.name, class: "product-item", type: "submit"
  - active = (codes_list && codes_list.include?(model.code)) ? "pressed" : ""
  =link_to remove_from_list_path(code: model.code), class: "product-count product-count-#{model.code} #{active}", remote: true, method: :delete do
    %span=model.quantity_in_list(session_id)

app/views/products/_product_price.html.haml
-quantity = model.quantity_in_list(session_id)
%span{:'data-price' => "#{price}"}
  - if quantity > 1
    ="#{price} р. (#{(quantity*price).round(2)} р.)"
  -else
    =price
    р.

app/views/products/index.html.erb
<%= render 'layouts/products_header' %>

<h1>Каталог продукции</h1>
<p class="text-center">Минимальный чек в магазине 3000 руб.</p>
<p class="text-center"><%= link_to "Скачать прайс в Excel", products_path(format: 'xls') %></p>
<div class="table-wrapper table-catalog">
  <%= datagrid_form_for @grid, :method => :get, :url => products_path %>
  
  <%= datagrid_table @grid %>
  <%= paginate(@grid.assets, :theme => 'twitter-bootstrap-3',
                              :pagination_class => "pagination-sm") %>
</div>

app/views/products/index.xls.erb
<table border="1">
  <tr>
    <td colspan="6">Прайс-лист фирмы ИП Осипов Сергей Васильевич (по всем разделам) за <%= Time.now.strftime("%d.%m.%Y") %></td>

  </tr>
  <tr><td></td><td></td><td></td><td></td><td></td><td></td></tr>
  <tr><td></td><td></td><td></td><td></td><td></td><td>=СУММ(F5:F27242)</td></tr>
  <tr>
    <th>Наименование товара</th>
    <th>Ед.</th>
    <th>Опт.цена</th>
    <th>Вал</th>
    <th>Кол.</th>
    <th>Сум.заказа</th>
  </tr>
  <% @products.each_with_index do |product, i| %>
    <% row = i + 5 %>
    <tr>
      <td><%= product.full_name %></td>
      <td>шт.</td>
      <td><%= product.price %></td>
      <td>руб</td>
      <td></td>
      <td><%= "=C#{row}*E#{row}" %></td>
    </tr>
  <% end %>
</table>