config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'
  
  resources :lists, param: :slug
  resources :products
  resources :contacts
  match '/upload', to: 'products#upload', via: :post
  match '/delete_price', to: 'products#delete_price', via: :get
  match '/remove_from_list', to: 'lists#remove_product', via: :delete
end

app/views/layouts/_products_header.html.erb
<header class="catalog">
  <a href="/" data-turbolinks="false" class="btn btn-primary">Торговый Дом Химик</a>

  <% if !current_page?(products_path) %>

    <a href="/products" data-turbolinks="false" class="btn btn-primary">Каталог</a>

  <% else %>

    <%= link_to list_path(slug: @session_id), turbolinks: false, class: "btn btn-primary" do %>
      К списку
      <% hidden = "hidden-only" if @codes_list.blank? %>
      <span class="products-count <%= hidden %>"><%= @codes_list.count if @codes_list %></span>
    <% end %>

  <% end %>

  <% if current_user %>
    <div class="dropdown dropdown-lists">
      <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu dropdown-menu-right">
        <% for list in @lists %>
          <li>
            <%= link_to list_path(slug: list.session_id) do %>
              <%= list.title %>
              <%= "(#{list.codes_list.count})" if @codes_list %>
            <% end %>
          </li>
        <% end %>

        <li><%= link_to "Мои списки", lists_path %></li>
      </ul>
    </div>
  <% end %>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109917857-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-109917857-1');
    </script>

    <title>Торговый Дом Химик</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="assets1/plugins/ionicons/css/ionicons.min.css">
    <script src='https://www.google.com/recaptcha/api.js'></script>
  </head>

  <body data-spy="scroll" data-target="#navbar_main" data-offset="80">
    <% flash.each do |key, value| %>
          <div class="flash_<%= key %>">
                <%= value.html_safe %>
          </div>
    <% end %>

    <% if Rails.env.development? %>
      <div class="flash_notice">
        cookies[:session_id] <%= cookies[:session_id] %> 
        current_session_id <%= current_user.current_session_id if current_user %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>